# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Название новости')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Изображение для анонса')),
                ('recom', models.ManyToManyField(blank=True, related_name='_item_recom_+', to='news.Item', verbose_name='Похожая новость')),
            ],
            options={
                'verbose_name_plural': 'Новости',
                'verbose_name': 'Новость',
                'ordering': ['title'],
                'default_related_name': 'Без названия',
            },
        ),
    ]
