# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-24 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_item_recom'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата новости'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='fulltext',
            field=models.TextField(blank=True, verbose_name='Текст новости'),
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='slug'),
        ),
    ]
