# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-24 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180124_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='fulltext',
            new_name='full_text',
        ),
    ]
