# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-25 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20180125_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='short_text',
            field=models.TextField(blank=True, verbose_name='Анонс новости'),
        ),
    ]
