# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-22 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=254, verbose_name='E-mail пользователя')),
            ],
            options={
                'default_related_name': 'Без названия',
                'verbose_name': 'Электронный адрес',
                'verbose_name_plural': 'Электронные адреса',
                'ordering': ['mail'],
            },
        ),
    ]
