# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-23 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['date_created'], 'verbose_name': 'Электронный адрес', 'verbose_name_plural': 'Электронные адреса'},
        ),
    ]
