# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-06 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171024_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.EmailField(max_length=254, verbose_name='E-mail пользователя'),
        ),
    ]
