# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Название игры')),
                ('description', models.TextField(blank=True, verbose_name='Описание игры')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_release', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
                ('language', models.IntegerField(blank=True, choices=[(1, 'русский'), (2, 'английский')], db_index=True, default=1, verbose_name='статус')),
            ],
            options={
                'default_related_name': 'Без названия',
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Название жанра')),
            ],
            options={
                'default_related_name': 'Без названия',
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Название издателя')),
            ],
            options={
                'default_related_name': 'Без названия',
                'verbose_name': 'Издатель',
                'verbose_name_plural': 'Издатели',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='genres', to='games.Genre', verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publishers', to='games.Publisher', verbose_name='Издатель'),
        ),
    ]
