# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='language',
            field=models.IntegerField(blank=True, choices=[(1, 'русский'), (2, 'английский')], db_index=True, null=True, verbose_name='статус'),
        ),
    ]
