# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20170629_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='store_activation',
            field=models.IntegerField(blank=True, choices=[(1, 'steam'), (2, 'origin')], db_index=True, null=True, verbose_name='активация'),
        ),
    ]
