# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='coast',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость'),
        ),
    ]
