# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_coast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='coast',
        ),
        migrations.AddField(
            model_name='game',
            name='my_coast',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость в рублях'),
        ),
        migrations.AddField(
            model_name='game',
            name='store_coast',
            field=models.IntegerField(blank=True, null=True, verbose_name='Официальная стоимость'),
        ),
    ]
