# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20170702_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='digiseller_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Digiseller ID'),
        ),
    ]
