# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_game_digiseller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='region',
            field=models.IntegerField(blank=True, choices=[(1, 'Страны СНГ'), (2, 'Только в России'), (3, 'Россия/Польша')], db_index=True, null=True, verbose_name='Региональные ограничения'),
        ),
        migrations.AlterField(
            model_name='game',
            name='method_activation',
            field=models.IntegerField(blank=True, choices=[(1, 'steam gift'), (2, 'steam key'), (3, 'origin key'), (4, 'uplay key')], db_index=True, null=True, verbose_name='способ активации'),
        ),
    ]
