# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20170708_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='region',
            field=models.IntegerField(blank=True, choices=[(1, 'Страны СНГ'), (2, 'Россия'), (3, 'Россия/Польша')], db_index=True, null=True, verbose_name='Региональные ограничения'),
        ),
    ]
