# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20170708_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='region_a',
            new_name='region',
        ),
    ]
