# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_auto_20170713_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='seo_description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='game',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='game',
            name='seo_title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Заголовок на странице'),
        ),
    ]
