# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_auto_20170713_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Название игры')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='Скриншот')),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='seo_title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Заголовок страницы'),
        ),
    ]
