# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_auto_20170719_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='screenshot',
        ),
        migrations.AddField(
            model_name='screenshot',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='games.Game', verbose_name='Игры'),
        ),
    ]
