# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-11 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_game_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='slug'),
        ),
    ]
