# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-17 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_genre_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Игра даром'),
        ),
    ]
