# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-27 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_game_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image_slide',
            field=models.ImageField(blank=True, null=True, upload_to='gamescover/', verbose_name='Изображение для слайда'),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenshots', to='games.Game', verbose_name='Скриншоты'),
        ),
    ]
