# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-27 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_auto_20170927_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_slide',
            field=models.BooleanField(default=False, verbose_name='Показать в слайде'),
        ),
    ]
