# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-01 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_game_is_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='in_stock',
            field=models.BooleanField(default=False, verbose_name='Товар в наличии'),
        ),
    ]
