# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-06 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0024_auto_20171106_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='sa_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Steam-account id_d'),
        ),
        migrations.AddField(
            model_name='game',
            name='sb_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Steambuy id_d'),
        ),
        migrations.AddField(
            model_name='game',
            name='sp_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Steampay id_d'),
        ),
        migrations.AddField(
            model_name='game',
            name='zz_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zaka id_d'),
        ),
    ]
