# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-18 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0027_game_is_special_block_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='В популярное'),
        ),
    ]
