# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-29 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0028_game_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='id_video',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='ID youtube ролика'),
        ),
    ]
