# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-02 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0029_game_id_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_special_block_2',
            field=models.BooleanField(default=False, verbose_name='Специальный блок №2'),
        ),
    ]
