# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-31 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0030_game_is_special_block_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_special_block_1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='is_special_block_2',
        ),
        migrations.AddField(
            model_name='game',
            name='is_special_block',
            field=models.BooleanField(default=False, verbose_name='В специальный блок'),
        ),
    ]
