# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-29 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0031_auto_20180731_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_case',
            field=models.BooleanField(default=False, verbose_name='Наличие в Case'),
        ),
    ]
