# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-07 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0032_game_is_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image_banner',
            field=models.ImageField(blank=True, null=True, upload_to='gamescover/', verbose_name='Баннер для спец. блока'),
        ),
    ]
