# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-07 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0034_auto_20180908_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_special_block_2',
            field=models.BooleanField(default=False, verbose_name='В специальный блок №2'),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_special_block_1',
            field=models.BooleanField(default=False, verbose_name='В специальный блок №1'),
        ),
    ]
