# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-11 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0035_auto_20180908_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_free',
        ),
        migrations.AlterField(
            model_name='game',
            name='method_activation',
            field=models.IntegerField(blank=True, choices=[(1, 'steam gift'), (2, 'steam ключ'), (3, 'origin ключ'), (4, 'uplay ключ'), (5, 'rockstar ключ')], db_index=True, null=True, verbose_name='способ активации'),
        ),
    ]
