# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-11 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0036_auto_20190211_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_special_block_1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='is_special_block_2',
        ),
    ]
