# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-11 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0039_auto_20190212_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='image_banner',
        ),
    ]
