# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-11 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0040_remove_game_image_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slide_text',
            field=models.TextField(blank=True, max_length=300, verbose_name='Текст для слайда'),
        ),
    ]
