# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-16 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0041_game_slide_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
