# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-12-10 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0042_genre_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Название режима')),
                ('slug', models.SlugField(blank=True, verbose_name='slug')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Режим',
                'verbose_name_plural': 'Режимы',
                'default_related_name': 'Без названия',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['order'], 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AddField(
            model_name='game',
            name='mode',
            field=models.ManyToManyField(blank=True, related_name='modes', to='games.Mode', verbose_name='Режим'),
        ),
    ]
