# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-23 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0043_auto_20191210_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parthner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parthner_title', models.CharField(max_length=254, verbose_name='Название партнера')),
                ('parthner_digi_id', models.CharField(max_length=254, verbose_name='ID товара')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'ordering': ['parthner_title'],
                'default_related_name': 'Без названия',
            },
        ),
        migrations.RemoveField(
            model_name='game',
            name='sa_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='sb_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='sp_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='zz_id',
        ),
        migrations.AddField(
            model_name='parthner',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parthners', to='games.Game', verbose_name='Партнеры'),
        ),
    ]
