# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-23 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0044_auto_20191223_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_title', models.CharField(max_length=254, verbose_name='Название партнера')),
                ('partner_digi_id', models.CharField(max_length=254, verbose_name='ID товара')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='games.Game', verbose_name='Партнеры')),
            ],
            options={
                'verbose_name_plural': 'Партнеры',
                'verbose_name': 'Партнер',
                'ordering': ['partner_title'],
                'default_related_name': 'Без названия',
            },
        ),
        migrations.RemoveField(
            model_name='parthner',
            name='game',
        ),
        migrations.DeleteModel(
            name='Parthner',
        ),
    ]
