# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-23 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0046_auto_20191223_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partner_title',
            field=models.IntegerField(blank=True, choices=[(1, 'steambuy.com'), (2, 'sfera2002')], db_index=True, null=True, verbose_name='Название партнера'),
        ),
    ]
